import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Info } from 'lucide-react';

interface PromptTestPanelProps {
  promptType: string;
}

const mockVisionResponse = {
  content_type: 'lifestyle',
  production_quality: 'semi_professional',
  composition: 'rule_of_thirds',
  lighting: 'golden_hour',
  color_palette: 'warm',
  style: 'casual',
  subject_count: 1,
  has_text_overlay: false,
  text_overlay_type: 'none',
  brand_logo_visible: false,
  is_selfie: false,
  emotion_level: 'medium',
  setting: 'outdoor',
  is_candid: true,
  is_portrait: false,
  season_indicators: 'summer',
  venue_type: 'city park',
  subject_type: 'person',
  camera_quality: 'smartphone_high',
  editorial_publishable: false,
};

const mockCaptionResponse = [
  { text: 'That golden hour glow hits different.', estimated_engagement: 0.058 },
  { text: 'Sunday vibes in the park.', estimated_engagement: 0.042 },
];

export function PromptTestPanel({ promptType }: PromptTestPanelProps) {
  const response = promptType === 'vision_tagging' ? mockVisionResponse : mockCaptionResponse;

  return (
    <Card>
      <div style={{ padding: 'var(--space-4)' }}>
        <div className="flex items-center justify-between" style={{ marginBottom: 'var(--space-3)' }}>
          <span className="t-sub">Test Output</span>
          <Badge variant="accent">Mock Response</Badge>
        </div>

        <div
          style={{
            padding: 'var(--space-3)',
            borderRadius: 'var(--radius)',
            background: 'var(--bg)',
            border: '1px solid var(--border)',
            marginBottom: 'var(--space-3)',
          }}
        >
          <div style={{ textAlign: 'center', padding: 'var(--space-4)', marginBottom: 'var(--space-3)', borderBottom: '1px solid var(--border)' }}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="https://picsum.photos/seed/content1/400/500"
              alt="Test image"
              style={{ maxWidth: 200, borderRadius: 'var(--radius)', margin: '0 auto', display: 'block' }}
            />
            <span className="t-caption" style={{ display: 'block', marginTop: 'var(--space-2)', color: 'var(--text-tertiary)' }}>
              Sample test image
            </span>
          </div>

          <pre
            style={{
              fontFamily: 'monospace',
              fontSize: 12,
              lineHeight: 1.5,
              whiteSpace: 'pre-wrap',
              margin: 0,
              color: 'var(--text-secondary)',
            }}
          >
            {JSON.stringify(response, null, 2)}
          </pre>
        </div>

        <div
          className="flex items-center gap-2"
          style={{
            padding: 'var(--space-3)',
            borderRadius: 'var(--radius)',
            background: 'color-mix(in srgb, var(--accent) 8%, transparent)',
            border: '1px solid color-mix(in srgb, var(--accent) 20%, transparent)',
            marginBottom: 'var(--space-3)',
          }}
        >
          <Info size={14} style={{ color: 'var(--accent)', flexShrink: 0 }} />
          <span className="t-caption" style={{ color: 'var(--text-secondary)' }}>
            These fields are generated by your Vision prompt. Edit the prompt on the left to change what gets tagged.
            The output fields populate the Content Explorer filters and the Trends dashboard.
          </span>
        </div>

        <button className="btn" style={{ width: '100%' }}>
          Run Test
        </button>
      </div>
    </Card>
  );
}
